# Generated by Django 4.1.7 on 2023-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_about_product_model_product_asset_product_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
