# Generated by Django 4.1.7 on 2023-04-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_items',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issued_items',
            name='warranty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issued_items',
            name='warrentyexpire',
            field=models.DateField(null=True),
        ),
    ]
